baseurl      = "localhost"
title        = "My Blog"
languageCode = "en-us"
theme        = "hugo-theme-hello-friend-ng"
paginate     = 10

[params]

  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
  # Subtitle for home
  homeSubtitle = "Indonesian. Passionate about software and design."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you linke
  enableSharingButtons = false

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

  # Default theme "light" or "dark"
  defaultTheme = "light"
  
  [params.portrait]
    path = "pp.jpg"
    alt = "tes"
    maxwidth = "250px"

  # [[params.portrait]]
    # path = "images/favicon.png"

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/GustafPahlevi"

  [[params.social]]
    name = "email"
    url  = "mailto:gustafpahlevi@gmail.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/GustafPahlevi"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/gustafpahlevi"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Hello World! I'm Gustaf."
    subtitle = "Gustaf Pahlevi | Software Engineer"
    keywords = ""
    copyright = 'Gustaf Pahlevi'
    # readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "root@server:"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/blog"